apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend-base-service
  name: frontend-base-service
  namespace: semen-sinapis
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend-base-service
  template:
    metadata:
      annotations:
        dapr.io/app-id: frontend-base-service
        dapr.io/app-port: '50000'
        dapr.io/app-protocol: grpc
        dapr.io/enabled: 'true'
        dapr.io/log-as-json: 'true'
        dapr.io/sidecar-liveness-probe-delay-seconds: '10'
        dapr.io/sidecar-readiness-probe-delay-seconds: '10'
        module.wasm.image/variant: compat-smart
      labels:
        app: frontend-base-service
    spec:
      containers:
      - command:
        - ./frontend-base-service
        env:
        - name: ADDR
          valueFrom:
            configMapKeyRef:
              key: ADDR
              name: frontend-base-service-cm
        - name: NACOS_HOST
          valueFrom:
            configMapKeyRef:
              key: NACOS_HOST
              name: frontend-base-service-cm
        - name: CONFIG_NAMESPACE
          valueFrom:
            configMapKeyRef:
              key: CONFIG_NAMESPACE
              name: frontend-base-service-cm
        image: 192.168.33.48/library/semen-sinapis/frontend-base-service:v0.0.1
        imagePullPolicy: Alaways
        name: frontend-base-service
        ports:
        - containerPort: 50000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend-base-service
  name: frontend-base-service-svc
  namespace: semen-sinapis
spec:
  ports:
  - port: 50000
    protocol: TCP
    targetPort: 50000
  selector:
    app: frontend-base-service
  type: ClusterIP
---
apiVersion: v1
data:
  ADDR: 0.0.0.0:50000
  CONFIG_NAMESPACE: semen-sinapis
  NACOS_HOST: nacos-cs:8848
kind: ConfigMap
metadata:
  labels:
    app: frontend-base-service
  name: frontend-base-service-cm
  namespace: semen-sinapis
