//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

pub mod prelude;

pub mod permission;
pub mod policy;
pub mod resource_type;
pub mod role;
pub mod role_parent;
pub mod role_permission;
pub mod role_policy;
pub mod user_info;
pub mod user_role;
pub mod organization;
