//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

pub use super::permission::Entity as Permission;
pub use super::policy::Entity as Policy;
pub use super::resource_type::Entity as ResourceType;
pub use super::role::Entity as Role;
pub use super::role_parent::Entity as RoleParent;
pub use super::role_permission::Entity as RolePermission;
pub use super::role_policy::Entity as RolePolicy;
pub use super::user_info::Entity as UserInfo;
pub use super::user_role::Entity as UserRole;
pub use super::organization::Entity as Organization;
